services:

  frontend:
    build: ./client
    container_name: employee-client
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build: ./server
    container_name: employee-server
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8
    container_name: employee-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: